# AUTH CALL #
# Variables
@base_URL=http://localhost:3000/api/auth


###
post {{base_URL}}
Content-Type: application/json

{
    "email": "robin.vandenbroucke2@student.vives.com",
    "password": "Robin"
}